### ISSUE TITLE
Is there fingerprint on display ?

### ISSUE THREAD

**Issue by ghost** [together08/device_xiaomi_psyche#1]
Does this device tree at present work with fingerprint or not

**Comment by together08** [comment]
The device tree is still under testing



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 07/24/2022 00:28 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [together08/device_xiaomi_psyche] Is there fingerprint on display ? (Issue #1) |

Is this device tree at present works with fingerprint or not

**Comment by ghost** [comment]
I have a device tree but it run into a *neverallow* error at the total progress of 58%.

I can't found where the origin file system_server.de is even though I located the error.

Thanks for reply !

**Comment by together08** [comment]
btw, You can set SELINUX_IGNORE_NEVERALLOWS := true in your device tree to fix that error.
My build has booted successfully.






| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 07/24/2022 07:36 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [together08/device_xiaomi_psyche] Is there fingerprint on display ? (Issue #1) |

Closed #1 as completed.

**Comment by ghost** [comment]
> btw, You can set SELINUX_IGNORE_NEVERALLOWS := true in your device tree to fix that error. My build has booted successfully. | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 07/24/2022 07:36 | | To | ***@***.***> | | Cc | ***@***.******@***.***> | | Subject | Re: [together08/device_xiaomi_psyche] Is there fingerprint on display ? (Issue #1) | Closed #1 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Tranks ! I'll try it.
